config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'pages/home'
  post '/submit_form', to: 'pages#submit_form'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @submitted = false
  end

  def submit_form
    # Access form data using the params hash
    
    @pet = params[:pet_name]
    @city = params[:city]
    @image = params[:bbkk]
    @slider = params[:slider].to_i
    @submitted = true

    puts(@pet)
    puts(@city)

    @city.chomp!
    @pet.chomp!

    start_fart = @pet[0]
    start_bruh = @city[0]
    @city[0] = start_bruh
    @pet[0] = start_fart

    fart = @pet
    bruh = @city

    if fart > bruh
      portmanteau = bruh + fart
    else
      portmanteau = fart + bruh
    end

    if @image == "kiki"
      if portmanteau.include? "k"
        portmanteau.gsub!("k", "c")
      end
      if portmanteau.include? "i"
        portmanteau.gsub!("i", "e")
      end
    elsif @image == "booba"
      if portmanteau.include? "b"
        portmanteau.gsub!("b", "d")
      end
      if portmanteau.include? "o"
        portmanteau.gsub!("o", "u")
      end
    end

    if @slider > portmanteau.length
      diffski = ((@slider - portmanteau.length) - 1)
      revPortmanteau = portmanteau.reverse
      startRevPort = revPortmanteau[0..diffski]
      newPort = portmanteau + startRevPort 
    elsif @slider < portmanteau.length
      diffski = ((portmanteau.length - @slider) - 1)
      newPort = portmanteau[0..-1-diffski]
    else
      newPort = portmanteau
    end

    @newPort = newPort
    Rails.logger.debug(@newPort)
    render 'home'
  end
 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PasswordGenerator</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag 'application' %>
    <%= stylesheet_link_tag 'bootstrap' %>
    <%= javascript_include_tag 'bootstrap' %>
    <%= stylesheet_link_tag 'homestyle', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>



  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/_params.html.erb
<script>
  console.log('Checking to see if we submitted');
</script>

<style>
  .form-field {
    display: flex;
    flex-direction: column;
    align-items: center;
    text-align: center;
    border: 3px solid green;
    padding: 10px;
  }

  .form-field h2,
  .form-field p {
    margin: 0;
  }
</style>

<div class="form-field">
  <h2>New Password: </h2> 
  <%= @newPort %>
</div>

app/views/pages/home.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <div class="form-container">
        <h1 class="form-field">Ultra High Tech Cyber Security Company Lock Safe Web Guard Password Generator</h1>
        <form id="myform" action="<%= submit_form_path %>" method="POST">
          <%= csrf_meta_tags %>
          <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
          <div class="form-group">
            <label for="pet-name">What was the name of your first pet/your mother's maiden name?</label>
            <div class="form-field">
              <input type="text" id="pet-name" name="pet_name">
            </div>
          </div>
          <div class="form-group">
            <label for="city">Where were you born:</label>
            <div class="form-field">
              <input type="text" id="city" name="city" maxlength="25">
            </div>
          </div>
          <div class="form-group">
            <label for="slider">Choose a number between 10 and 30:</label>
            <div class="form-field">
              <input type="range" id="slider" name="slider" min="10" max="30">
              <p id="sliderValue">0</p>
            </div>
          </div>
          <div class="form-group">
            <label for="image">Choose an image:</label>
            <div class="row">
              <div class="col-md-6 d-flex align-items-center">
                <img src="/assets/bouba.png" alt="Bouba" width="100" height="100">
                <div class="ml-3 form-field">
                  <input class="form-check-input" type="radio" name="bbkk" id="Bouba" value="Booba">
                  <label class="form-check-label" for="Bouba">
                    Bouba
                  </label>
                </div>
              </div>
              <div class="col-md-6 d-flex align-items-center">
                <img src="/assets/kiki.png" alt="Kiki" width="100" height="100">
                <div class="ml-3 form-field">
                  <input class="form-check-input" type="radio" name="bbkk" id="Kiki" value="Kiki">
                  <label class="form-check-label" for="Kiki">
                    Kiki
                  </label>
                </div>
              </div>
            </div>
          </div>
          <button type="submit" class="btn btn-primary">Submit</button>
        </form>
      </div>
    </div>
  </div>
</div>

<%= render partial: 'pages/params', locals: { newPort: @newPort } %>